version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.miner
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - bitcoin-core
    command: ["./start.sh"]

  cpuminer-opt:
    build:
      context: .
      dockerfile: Dockerfile.cpuminer-opt
    depends_on:
      - bitcoin-core
    command: ["./start-cpuminer-opt.sh"]
    # https://docs.docker.com/compose/compose-file/deploy/
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1GB

  bitcoin-core:
    build:
      context: .
      dockerfile: Dockerfile.btc
      args:
        TARGETPLATFORM: "linux/amd64"
    volumes:
      - ./btc/:/home/bitcoin/.bitcoin
    environment:
      - UID=$UID
      - GID=$GID
    command:
      -printtoconsole
